# Site settings
title: "Open your mind! Go ahead, Trysome!"
email: "rfk@gotrysome.com"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.gotrysome.com" # the base hostname & protocol for your site
twitter_username: trysome
github_username:  trysome

# Build settings
markdown: kramdown

sass:
  style: :compressed
  sass_dir: _sass

gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']